import { createHashRouter, Link, NavLink, Outlet, useParams } from "react-router";
import { RouterProvider } from "react-router/dom";
import { useEffect, useMemo, useState } from "react";
import Fuse from "fuse.js";
import { formatDate, repositoryUrl } from "../lib/portal-data";
import { usePortalData, PortalDataProvider } from "./PortalDataContext";
import type { KnowledgeGraph, KnowledgeNode, PortalStats, SectionIndex } from "../types";
import { MarkdownDocument } from "../features/topic/MarkdownDocument";
import { TopicList } from "../components/TopicList";
import { buildSectionIndex, derivedStats } from "../lib/portal-data";

function PortalShell() {
  const { nodes, sections, stats } = usePortalData();
  const [query, setQuery] = useState("");
  const fuse = useMemo(
    () =>
      new Fuse(nodes, {
        keys: ["title", "summary", "notes", "sections", "tags", "keywords"],
        threshold: 0.3,
      }),
    [nodes],
  );
  const searchResults = query ? fuse.search(query).map(({ item }) => item) : [];

  return (
    <div className="portal-shell">
      <header className="site-header">
        <div className="masthead">
          <Link className="logo" to="/">
            <span aria-hidden="true" className="logo-mark">
              KG
            </span>
            <span className="logo-copy">
              <strong>KnowlegeGraph</strong>
              <small>Simple knowledge site</small>
            </span>
          </Link>
          <nav className="primary-nav" aria-label="Primary navigation">
            <NavLink end to="/">
              Topics
            </NavLink>
            <NavLink to="/search">Search</NavLink>
            <NavLink to="/graph">Graph</NavLink>
            <NavLink to="/timeline">Timeline</NavLink>
            <NavLink to="/stats">Stats</NavLink>
          </nav>
          <a className="github-link" href={repositoryUrl()} target="_blank" rel="noreferrer">
            GitHub
          </a>
        </div>
        <div className="utility-bar">
          <div className="global-search">
            <span aria-hidden="true">⌕</span>
            <input
              aria-label="Search your knowledge"
              value={query}
              onChange={(event) => setQuery(event.target.value)}
              placeholder="Search topics, tags, sections…"
            />
            {query && (
              <div className="search-results">
                {searchResults.slice(0, 6).map((node) => (
                  <Link key={node.id} to={`/topic/${node.slug}`} onClick={() => setQuery("")}>
                    <strong>{node.title}</strong>
                    <small>{node.sections.join(" · ")}</small>
                  </Link>
                ))}
              </div>
            )}
          </div>
          <div className="section-links" aria-label="Sections">
            {sections.slice(0, 5).map((section) => (
              <Link key={section.name} to={`/section/${encodeURIComponent(section.name)}`}>
                {section.name}
                <span>{section.count}</span>
              </Link>
            ))}
          </div>
        </div>
      </header>
      <main>
        <section className="page">
          <Outlet />
        </section>
        <footer>Generated by KnowlegeGraph · Markdown is the source of truth.</footer>
      </main>
    </div>
  );
}

function TopicHome() {
  const { nodes, stats } = usePortalData();
  const recent = [...nodes].sort((a, b) => b.updatedAt.localeCompare(a.updatedAt));
  return (
    <div className="home-page">
      <section className="home-intro">
        <div>
          <p className="eyebrow">Knowledge topics</p>
          <h1>Simple notes, linked by idea.</h1>
        </div>
        <div className="intro-note">
          <p>A minimal reading list for systems, software, and the links between them.</p>
          <div className="stats-inline">
            <span>
              <strong>{stats.topics}</strong> topics
            </span>
            <span>
              <strong>{stats.sections}</strong> sections
            </span>
            <span>
              <strong>{stats.resources}</strong> links
            </span>
          </div>
        </div>
      </section>
      <TopicList nodes={recent} />
    </div>
  );
}

function SearchRoute() {
  const { nodes } = usePortalData();
  const [query, setQuery] = useState("");
  const fuse = useMemo(
    () =>
      new Fuse(nodes, {
        keys: ["title", "summary", "notes", "sections", "tags", "keywords"],
        threshold: 0.3,
      }),
    [nodes],
  );
  const results = query.trim() ? fuse.search(query).map(({ item }) => item) : nodes;
  return (
    <>
      <div className="page-heading">
        <p className="eyebrow">Search</p>
        <h1 className="page-title">Find a topic.</h1>
        <p className="lede">Search titles, summaries, sections, tags, and notes.</p>
      </div>
      <input
        className="large-search"
        aria-label="Search all entries"
        autoFocus
        value={query}
        onChange={(event) => setQuery(event.target.value)}
        placeholder="Topic, tag, section, or keyword…"
      />
      <p className="result-count" aria-live="polite">
        {results.length} {results.length === 1 ? "topic" : "topics"}
      </p>
      <TopicList nodes={results} />
    </>
  );
}

function SectionRoute() {
  const { nodes } = usePortalData();
  const { name = "" } = useParams();
  const selected = nodes.filter((node) => node.sections.includes(name));
  return (
    <>
      <p className="breadcrumb">
        <Link to="/">Home</Link> / Sections / {name}
      </p>
      <div className="page-heading">
        <p className="eyebrow">Section</p>
        <h1 className="page-title">{name}</h1>
        <p className="lede">{selected.length} topics in this section.</p>
      </div>
      <TopicList nodes={selected} />
    </>
  );
}

function TopicRoute() {
  const { nodes } = usePortalData();
  const { slug = "" } = useParams();
  const node = nodes.find((candidate) => candidate.slug === slug);
  const markdownUrl = `./knowledge/nodes/${encodeURIComponent(slug)}.md`;
  const [markdown, setMarkdown] = useState("");

  useEffect(() => {
    setMarkdown("");
    fetch(markdownUrl)
      .then((response) => (response.ok ? response.text() : Promise.reject()))
      .then(setMarkdown)
      .catch(() => {
        if (node && import.meta.env.DEV) {
          setMarkdown(`# ${node.title}\n\n## Overview\n\n${node.summary}\n\n## Notes\n\nPortal preview content.`);
        }
      });
  }, [markdownUrl, node]);

  if (!node) {
    return (
      <div className="empty-panel">
        Topic not found. <Link to="/">Return home</Link>
      </div>
    );
  }

  const related = node.relations
    .map((relation) => ({ relation, node: nodes.find((item) => item.id === relation.targetId) }))
    .filter((item): item is { relation: (typeof node.relations)[number]; node: KnowledgeNode } => Boolean(item.node));

  return (
    <>
      <p className="breadcrumb">
        <Link to="/">Home</Link> / <Link to={`/section/${encodeURIComponent(node.sections[0] ?? "Unsorted")}`}>{node.sections[0] ?? "Unsorted"}</Link> / {node.title}
      </p>
      <article className="topic-layout">
        <div>
          <header className="topic-header">
            <div className="tag-row">
              {node.sections.map((value) => <span key={value}>{value}</span>)}
              {node.tags.map((value) => <span className="tag" key={value}>{value}</span>)}
            </div>
            <h1 className="page-title">{node.title}</h1>
            {node.summary && <p className="topic-summary">{node.summary}</p>}
            <p className="topic-updated">
              Last updated <time dateTime={node.updatedAt}>{formatDate(node.updatedAt)}</time> · {node.resources.length}{" "}
              {node.resources.length === 1 ? "link" : "links"}
            </p>
          </header>
          {markdown ? <MarkdownDocument markdown={markdown} /> : <div className="loading">Loading topic…</div>}
        </div>
        <aside className="topic-aside">
          <div>
            <h3>Links</h3>
            {node.resources.length ? (
              node.resources.map((resource) => (
                <a key={resource.url} href={resource.url} target="_blank" rel="noreferrer">
                  <span>{resource.title || resource.website}</span>
                  <small>{resource.website || resource.type} ↗</small>
                </a>
              ))
            ) : (
              <p>No links attached.</p>
            )}
          </div>
          <div>
            <h3>Related topics</h3>
            {related.length ? (
              related.map(({ relation, node: relatedNode }) => (
                <Link key={relation.targetId} to={`/topic/${relatedNode.slug}`}>
                  <span>{relatedNode.title}</span>
                  <small>{relation.type}</small>
                </Link>
              ))
            ) : (
              <p>No related topics yet.</p>
            )}
          </div>
        </aside>
      </article>
    </>
  );
}

function GraphRoute() {
  const { nodes } = usePortalData();
  return (
    <>
      <div className="page-heading">
        <p className="eyebrow">Graph</p>
        <h1 className="page-title">Connections</h1>
        <p className="lede">A simple map of how topics relate to each other.</p>
      </div>
      <TopicList nodes={[...nodes].sort((a, b) => b.relations.length - a.relations.length)} />
    </>
  );
}

function TimelineRoute() {
  const { nodes } = usePortalData();
  const months = [...nodes]
    .sort((a, b) => b.createdAt.localeCompare(a.createdAt))
    .reduce<Record<string, KnowledgeNode[]>>((result, node) => {
      const month = new Date(node.createdAt).toLocaleDateString(undefined, {
        month: "long",
        year: "numeric",
      });
      result[month] = [...(result[month] ?? []), node];
      return result;
    }, {});
  return (
    <>
      <div className="page-heading">
        <p className="eyebrow">Timeline</p>
        <h1 className="page-title">Reading history</h1>
        <p className="lede">A chronological index of when each topic was added.</p>
      </div>
      <div className="timeline">
        {Object.entries(months).map(([month, items]) => (
          <section key={month}>
            <h2>{month}</h2>
            <TopicList nodes={items ?? []} />
          </section>
        ))}
      </div>
    </>
  );
}

function StatsRoute() {
  const { nodes, stats } = usePortalData();
  const cards: Array<[string, string | number]> = [
    ["Topics", stats.topics],
    ["Sections", stats.sections],
    ["Links", stats.resources],
    ["Relationships", stats.relationships],
  ];
  return (
    <>
      <div className="page-heading">
        <p className="eyebrow">Stats</p>
        <h1 className="page-title">Library index</h1>
        <p className="lede">A quick look at the size and shape of the collection.</p>
      </div>
      <div className="metric-grid">
        {cards.map(([label, value]) => (
          <div key={label}>
            <strong>{value}</strong>
            <span>{label}</span>
          </div>
        ))}
      </div>
      <TopicList nodes={[...nodes].sort((a, b) => b.relations.length - a.relations.length)} />
    </>
  );
}

const router = createHashRouter([
  {
    path: "/",
    element: <PortalShell />,
    children: [
      { index: true, element: <TopicHome /> },
      { path: "search", element: <SearchRoute /> },
      { path: "section/:name", element: <SectionRoute /> },
      { path: "topic/:slug", element: <TopicRoute /> },
      { path: "graph", element: <GraphRoute /> },
      { path: "timeline", element: <TimelineRoute /> },
      { path: "stats", element: <StatsRoute /> },
    ],
  },
]);

export function PortalRouter({
  graph,
  sections,
  stats,
}: {
  graph: KnowledgeGraph;
  sections: SectionIndex["sections"];
  stats: PortalStats;
}) {
  const active = graph.nodes.filter((node) => !node.archived);
  return (
    <PortalDataProvider value={{ nodes: active, sections: sections.length ? sections : buildSectionIndex(active), stats: stats ?? derivedStats(active) }}>
      <RouterProvider router={router} />
    </PortalDataProvider>
  );
}
